name: build

on: [push]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
        uses: actions/checkout@v1

      - name: "get buildTools"
        uses: ModelingValueGroup/buildTools@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "install packages for tests"
        run: sudo apt-get install xmlstarlet jq maven

      - name: "setup JDK"
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: "get dependencies (as in pom)"
        run:  . buildTools.sh && mvn_ dependency:copy-dependencies -DoutputDirectory=lib

      - name: "..."
        run:  ls -la . lib

      - name: "generate sources"
        run:  |
          ant compile.module.build
          java -cp out/production/build EolCorrector
          java -cp out/production/build HeaderGenerator
          java -cp out/production/build StructGenerator

      - name: "forced stop"
        run:  exit 99
