name: build

on: [push]

env:
  GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
  ALLREP_TOKEN: "${{secrets.ALLREP_TOKEN}}"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: "checkout"
        uses: actions/checkout@v1

      - name: "attach head"
        run: git checkout "${GITHUB_REF#refs/heads/}"

      - name: "setup JDK"
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: "get buildtools"
        uses: ModelingValueGroup/buildtools@master

      - name: "get generic info" # for header file used below
        uses: ModelingValueGroup/generic-info@master

      - name: "(re)generate some files"
        run:  |
          . <(java -jar ~/buildtools.jar)
          generateAll
          cat <<EOF >build.properties
          jdk.home.11=$JAVA_HOME
          path.variable.maven_repository=$HOME/.m2/repository
          EOF
          ant compile.module.build
          java -cp out/production/build generator.StructGenerator "25" "immutable-collections/src" "org.modelingvalue.collections.struct"
          correctEols
          correctHeaders header

      - name: "push changes back to github"
        run:  |
          . <(java -jar ~/buildtools.jar)
          pushBackToGithub

      #=========== build & test: ===================================================================
      - name: "download dependencies (as mentioned in pom)"
        run:  |
          . <(java -jar ~/buildtools.jar)
          getAllDependencies "${{secrets.SCALEWAY_ACCESS_KEY}}" "${{secrets.SCALEWAY_SECRET_KEY}}"
          installJunitlauncher

      - name: "build"
        run:  ant

      - name: "test"
        run:  |
          if ! ant test; then
            for i in TEST-*.xml; do
              echo "=============== $i"
              sed "s/^/>> /" $i
            done
            exit 42
          fi

      - name: "generate javadoc"
        run:  ant javadoc

      #=========== publish: ===================================================================
      - name: "publish action-artifact jar"
        uses: actions/upload-artifact@v1
        with:
          name: immutable-collections.jar
          path: out/artifacts/immutable-collections.jar

      - name: "publish action-artifact sources"
        uses: actions/upload-artifact@v1
        with:
          name: immutable-collections-sources.jar
          path: out/artifacts/immutable-collections-sources.jar

      - name: "publish action-artifact javadoc"
        uses: actions/upload-artifact@v1
        with:
          name: immutable-collections-javadoc.jar
          path: out/artifacts/immutable-collections-javadoc.jar

      - name: "publish action-artifact test-results"
        uses: actions/upload-artifact@v1
        with:
          name: immutable-collections-testresults.jar
          path: out/artifacts/immutable-collections-testresults.jar

  snapshots:
    runs-on: ubuntu-20.04
    if: github.ref != 'refs/heads/master'
    needs: build
    steps:
      - name: "checkout"
        uses: actions/checkout@v1

      - name: "get buildtools"
        uses: ModelingValueGroup/buildtools@master

      - name: "get downloads"
        uses: actions/download-artifact@v2
        with:
          path: out/artifacts

      - name: "saving snapshots for other projects on this branch"
        run: |
          . <(java -jar ~/buildtools.jar)
          mv out/artifact/*/* out/artifact
          rmdir out/artifact/* 2>/dev/null
          find out -exec -l -l {} +
          storeMyBranchSnapshots

  publish:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/master'
    needs: build
    steps:
      - name: "checkout"
        uses: actions/checkout@v1

      - name: "get buildtools"
        uses: ModelingValueGroup/buildtools@master

      - name: "get downloads"
        uses: actions/download-artifact@v2
        with:
          path: out/artifacts

      - name: "tag with version"
        run: |
          . <(java -jar ~/buildtools.jar)
          setVersionTag
          mv out/artifact/*/* out/artifact
          rmdir out/artifact/* 2>/dev/null
          find out -exec -l -l {} +

      - name: "publish maven-artifacts (jar/pom/sources/javadoc)"
        uses: ModelingValueGroup/upload-maven-package-action@master
        with:
          file : "out/artifact/immutable-collections.jar"
