name: build

on: [push]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
        uses: actions/checkout@v1

      - name: "get buildTools"
        uses: ModelingValueGroup/buildTools@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "install packages for building"
        run: sudo apt-get install xmlstarlet jq maven

      - name: "setup JDK"
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: "get dependencies (as in pom)"
        run:  |
          . buildTools.sh
          mkdir -p lib
          mvn_ ${{ secrets.GITHUB_TOKEN }} dependency:copy-dependencies -DoutputDirectory=lib

      - name: "(re)generate sources"
        run:  |
          ant -Djdk.home.11=$JAVA_HOME compile.module.build
          java -cp out/production/build EolCorrector
          java -cp out/production/build HeaderGenerator
          java -cp out/production/build StructGenerator

      - name: "push changes back"
        run:  |
          git status
          if [[ -f changes-detected ]]; then
            git status # TODO: change this to commit&push
          fi

      - name: "forced stop"
        run:  exit 99
