name: build

on: [push]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
        uses: actions/checkout@v1

      - name: "attach head"
        run: git checkout "${GITHUB_REF#refs/heads/}"

      - name: "setup JDK"
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: "get buildTools"
        uses: ModelingValueGroup/buildTools@develop
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "debug"
        run:  |
          find . -type f | sed 's/^/@@@/'

      - name: "prepare ant"
        run:  |
          cat <<EOF >build.properties
          jdk.home.11=$JAVA_HOME
          path.variable.maven_repository=$HOME/.m2/repository
          EOF

      - name: "(re)generate some files"
        run:  |
          . <(java -jar buildTools.jar)
          updateAllPomsFromIntellijDependencies
          generateAntTestFilesFromIntellij
          generateAntJavadocFilesFromIntellij
          cleanupIntellijAntFiles
          ant compile.module.build
          java -cp out/production/build StructGenerator "25" "immutable-collections/src" "org.modelingvalue.collections.struct"
          correctEols
          correctHeaders header

      - name: "download dependencies (as mentioned in pom)"
        run:  |
          . <(java -jar buildTools.jar)
          mkdir -p lib
          mvn_ ${{ secrets.GITHUB_TOKEN }} dependency:copy-dependencies -DoutputDirectory=lib

      - name: "build"
        run:  ant

      - name: "test"
        run:  ant test.results.jar.immutable-collections

      - name: "javadoc"
        run:  ant javadoc.module.immutable-collections

      - name: "upload immutable-collections.jar"
        uses: actions/upload-artifact@v1
        with:
          name: jdclare.jar
          path: out/artifacts/immutable-collections.jar

      - name: "upload immutable-collections-sources.jar"
        uses: actions/upload-artifact@v1
        with:
          name: immutable-collections-sources.jar
          path: out/artifacts/immutable-collections-sources.jar

      - name: "upload immutable-collections-javadoc.jar"
        uses: actions/upload-artifact@v1
        with:
          name: immutable-collections-javadoc.jar
          path: out/artifacts/immutable-collections-javadoc.jar

      - name: "upload immutable-collections-testresults.jar"
        uses: actions/upload-artifact@v1
        with:
          name: immutable-collections-testresults.jar
          path: out/artifacts/immutable-collections-testresults.jar

      - name: "push changes back to github"
        run:  |
          if [[ "$(git ls-files -o --exclude-standard)" ]]; then
            echo "changes need to be pushed back to github"

            echo "::group::git commit and push"
              git config user.email "automation@modelingvalue.com"
              git config user.name "$GITHUB_ACTOR"
              git add .
              git commit -m "adjusted files [by github actions]"
              git push "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
            echo "::endgroup::"

          else
            echo "no changes need to be pushed back to github"
          fi

      - name: "upload as package"
        uses: ModelingValueGroup/upload-maven-package-action@develop
        if: github.ref == 'refs/heads/master'
        with:
          file: "out/artifacts/immutable-collections.jar"
          token: "${{ secrets.GITHUB_TOKEN }}"
